In [1]:
import numpy as np
import pandas as pd
import sklearn

In [2]:
movies=pd.read_csv('tmdb_5000_movies.csv')
credits=pd.read_csv('tmdb_5000_credits.csv')

In [3]:
movies.head(30)

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2009-12-10,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2007-05-19,961000000,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500
2,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.sonypictures.com/movies/spectre/,206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,Spectre,A cryptic message from Bondâ€™s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...","[{""iso_3166_1"": ""GB"", ""name"": ""United Kingdom""...",2015-10-26,880674609,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466
3,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",http://www.thedarkknightrises.com/,49026,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-07-16,1084939099,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106
4,260000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://movies.disney.com/john-carter,49529,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-03-07,284139100,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124
5,258000000,"[{""id"": 14, ""name"": ""Fantasy""}, {""id"": 28, ""na...",http://www.sonypictures.com/movies/spider-man3/,559,"[{""id"": 851, ""name"": ""dual identity""}, {""id"": ...",en,Spider-Man 3,The seemingly invincible Spider-Man goes up ag...,115.699814,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2007-05-01,890871626,139.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,The battle within.,Spider-Man 3,5.9,3576
6,260000000,"[{""id"": 16, ""name"": ""Animation""}, {""id"": 10751...",http://disney.go.com/disneypictures/tangled/,38757,"[{""id"": 1562, ""name"": ""hostage""}, {""id"": 2343,...",en,Tangled,When the kingdom's most wanted-and most charmi...,48.681969,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2010-11-24,591794936,100.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,They're taking adventure to new lengths.,Tangled,7.4,3330
7,280000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://marvel.com/movies/movie/193/avengers_ag...,99861,"[{""id"": 8828, ""name"": ""marvel comic""}, {""id"": ...",en,Avengers: Age of Ultron,When Tony Stark tries to jumpstart a dormant p...,134.279229,"[{""name"": ""Marvel Studios"", ""id"": 420}, {""name...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2015-04-22,1405403694,141.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,A New Age Has Come.,Avengers: Age of Ultron,7.3,6767
8,250000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://harrypotter.warnerbros.com/harrypottera...,767,"[{""id"": 616, ""name"": ""witch""}, {""id"": 2343, ""n...",en,Harry Potter and the Half-Blood Prince,"As Harry begins his sixth year at Hogwarts, he...",98.885637,"[{""name"": ""Warner Bros."", ""id"": 6194}, {""name""...","[{""iso_3166_1"": ""GB"", ""name"": ""United Kingdom""...",2009-07-07,933959197,153.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,Dark Secrets Revealed,Harry Potter and the Half-Blood Prince,7.4,5293
9,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.batmanvsupermandawnofjustice.com/,209112,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 7002...",en,Batman v Superman: Dawn of Justice,Fearing the actions of a god-like Super Hero l...,155.790452,"[{""name"": ""DC Comics"", ""id"": 429}, {""name"": ""A...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2016-03-23,873260194,151.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,Justice or revenge,Batman v Superman: Dawn of Justice,5.7,7004
10,270000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://www.superman.com,1452,"[{""id"": 83, ""name"": ""saving the world""}, {""id""...",en,Superman Returns,Superman returns to discover his 5-year absenc...,57.925623,"[{""name"": ""DC Comics"", ""id"": 429}, {""name"": ""L...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2006-06-28,391081192,154.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,NaN,Superman Returns,5.4,1400
11,200000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 28, ""...",http://www.mgm.com/view/movie/234/Quantum-of-S...,10764,"[{""id"": 627, ""name"": ""killing""}, {""id"": 1568, ...",en,Quantum of Solace,Quantum of Solace continues the adventures of ...,107.928811,"[{""name"": ""Eon Productions"", ""id"": 7576}]","[{""iso_3166_1"": ""GB"", ""name"": ""United Kingdom""...",2008-10-30,586090727,106.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,"For love, for hate, for justice, for revenge.",Quantum of Solace,6.1,2965
12,200000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,58,"[{""id"": 616, ""name"": ""witch""}, {""id"": 663, ""na...",en,Pirates of the Caribbean: Dead Man's Chest,Captain Jack Sparrow works his way out of a bl...,145.847379,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...","[{""iso_3166_1"": ""JM"", ""name"": ""Jamaica""}, {""is...",2006-06-20,1065659812,151.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Jack is back!,Pirates of the Caribbean: Dead Man's Chest,7.0,5246
13,255000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://disney.go.com/the-lone-ranger/,57201,"[{""id"": 1556, ""name"": ""texas""}, {""id"": 2673, ""...",en,The Lone Ranger,The Texas Rangers chase down a gang of outlaws...,49.046956,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2013-07-03,89289910,149.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,Never Take Off the Mask,The Lone Ranger,5.9,2311
14,225000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.manofsteel.com/,49521,"[{""id"": 83, ""name"": ""saving the world""}, {""id""...",en,Man of Steel,A young boy learns that he has extraordinary p...,99.398009,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...","[{""iso_3166_1"": ""GB"", ""name"": ""United Kingdom""...",2013-06-12,662845518,143.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,You will believe that a man can fly.,Man of Steel,6.5,6359
15,225000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 10751...",NaN,2454,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",en,The Chronicles of Narnia: Prince Caspian,One year after their incredible adventures in ...,53.978602,"[{""name"": ""Walt Disney"", ""id"": 5888}, {""name"":...","[{""iso_3166_1"": ""CZ"", ""name"": ""Czech Republic""...",2008-05-15,419651413,150.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,Hope has a new face.,The Chronicles of Narnia: Prince Caspian,6.3,1630
16,220000000,"[{""id"": 878, ""name"": ""Science Fiction""}, {""id""...",http://marvel.com/avengers_movie/,24428,"[{""id"": 242, ""name"": ""new york""}, {""id"": 5539,...",en,The Avengers,When an unexpected enemy emerges and threatens...,144.448633,"[{""name"": ""Paramount Pictures"", ""id"": 4}, {""na...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-04-25,1519557910,143.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,Some assembly required.,The Avengers,7.4,11776
17,380000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 28, ""...",http://disney.go.com/pirates/index-on-stranger...,1865,"[{""id"": 658, ""name"": ""sea""}, {""id"": 1316, ""nam...",en,Pirates of the Caribbean: On Stranger Tides,Captain Jack Sparrow crosses paths with a woma...,135.413856,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2011-05-14,1045713802,136.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Live Forever Or Die Trying.,Pirates of the Caribbean: On Stranger Tides,6.4,4948
18,225000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 35, ""nam...",http://www.sonypictures.com/movies/meninblack3/,41154,"[{""id"": 4379, ""name"": ""time travel""}, {""id"": 5...",en,Men in Black 3,Agents J (Will Smith) and K (Tommy Lee Jones) ...,52.035179,"[{""name"": ""Amblin Entertainment"", ""id"": 56}, {...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-05-23,624026776,106.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,They are back... in time.,Men in Black 3,6.2,4160
19,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.thehobbit.com/,122917,"[{""id"": 417, ""name"": ""corruption""}, {""id"": 603...",en,The Hobbit: The Battle of the Five Armies,Immediately after the events of The Desolation...,120.965743,"[{""name"": ""WingNut Films"", ""id"": 11}, {""name"":...","[{""iso_3166_1"": ""NZ"", ""name"": ""New Zealand""}, ...",2014-12-10,956019788,144.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,Witness the defining chapter of the Middle-Ear...,The Hobbit: The Battle of the Five Armies,7.1,4760
20,215000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.theamazingspiderman.com,1930,"[{""id"": 1872, ""name"": ""loss of father""}, {""id""...",en,The Amazing Spider-Man,Peter Parker is an outcast high schooler aband...,89.866276,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-06-27,752215857,136.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The untold story begins.,The Amazing Spider-Man,6.5,6586
21,200000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.robinhoodthemovie.com/,20662,"[{""id"": 4147, ""name"": ""robin hood""}, {""id"": 43...",en,Robin Hood,When soldier Robin happens upon the dying Robe...,37.668301,"[{""name"": ""Imagine Entertainment"", ""id"": 23}, ...","[{""iso_3166_1"": ""GB"", ""name"": ""United Kingdom""...",2010-05-12,310669540,140.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,"Rise and rise again, until lambs become lions.",Robin Hood,6.2,1398
22,250000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://www.thehobbit.com/,57158,"[{""id"": 603, ""name"": ""elves""}, {""id"": 604, ""na...",en,The Hobbit: The Desolation of Smaug,"The Dwarves, Bilbo and Gandalf have successful...",94.370564,"[{""name"": ""WingNut Films"", ""id"": 11}, {""name"":...","[{""iso_3166_1"": ""NZ"", ""name"": ""New Zealand""}, ...",2013-12-11,958400000,161.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,Beyond darkness... beyond desolation... lies t...,The Hobbit: The Desolation of Smaug,7.6,4524
23,180000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://www.goldencompassmovie.com/index_german...,2268,"[{""id"": 392, ""name"": ""england""}, {""id"": 1461, ...",en,The Golden Compass,"After overhearing a shocking secret, precociou...",42.990906,"[{""name"": ""New Line Cinema"", ""id"": 12}, {""name...","[{""iso_3166_1"": ""GB"", ""name"": ""United Kingdom""...",2007-12-04,372234864,113.0,"[{""iso_639_1"": ""is"", ""name"": ""\u00cdslenska""},...",Released,There are worlds beyond our own - the compass ...,The Golden Compass,5.8,1303
24,207000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 18, ""...",NaN,254,"[{""id"": 774, ""name"": ""film business""}, {""id"": ...",en,King Kong,"In 1933 New York, an overly ambitious movie pr...",61.226010,"[{""name"": ""WingNut Films"", ""id"": 11}, {""name"":...","[{""iso_3166_1"": ""NZ"", ""name"": ""New Zealand""}, ...",2005-12-14,550000000,187.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The eighth wonder of the world.,King Kong,6.6,2337
25,200000000,"[{""id"": 18, ""name"": ""Drama""}, {""id"": 10749, ""n...",http://www.titanicmovie.com,597,"[{""id"": 2580, ""name"": ""shipwreck""}, {""id"": 298...",en,Titanic,"84 years later, a 101-year-old woman named Ros...",100.025899,"[{""name"": ""Paramount Pictures"", ""id"": 4}, {""na...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",1997-11-18,1845034188,194.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Nothing on Earth could come between them.,Titanic,7.5,7562
26,250000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 28, ""...",http://marvel.com/captainamericapremiere,271110,"[{""id"": 393, ""name"": ""civil war""}, {""id"": 6091...",en,Captain America: Civil War,"Following the events of Age of Ultron, the col...",198.372395,"[{""name"": ""Studio Babelsberg"", ""id"": 264}, {""n...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2016-04-27,1153304495,147.0,"[{""iso_639_1"": ""ro"", ""name"": ""Rom\u00e2n\u0103...",Released,Divided We Fall,Captain America: Civil War,7.1,7241
27,209000000,"[{""id"": 53, ""name"": ""Thriller""}, {""id"": 28, ""n...",NaN,44833,"[{""id"": 1721, ""name"": ""fight""}, {""id"": 4410, ""...",en,Battleship,"When mankind beams a radio signal into space, ...",64.928382,"[{""name"": ""Universal Pictures"", ""id"": 33}, {""n...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-04-11,303025485,131.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,The Battle for Earth Begins at Sea,Battleship,5.5,2114
28,150000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.jurassicworld.com/,135397,"[{""id"": 1299, ""name"": ""monster""}, {""id"": 1718,...",en,Jurassic World,Twenty-two years after the events of Jurassic ...,418.708552,"[{""name"": ""Universal Studios"", ""id"": 13}, {""na...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2015-06-09,1513528810,124.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The park is open.,Jurassic World,6.5,8662
29,200000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.skyfall-movie.com,37724,"[{""id"": 470, ""name"": ""spy""}, {""id"": 4289, ""nam...",en,Skyfall,When Bond's latest assignment goes gravely wro...,93.004993,"[{""name"": ""Columbia Pictures"", ""id"": 5}]","[{""iso_3166_1"": ""GB"", ""name"": ""United Kingdom""...",2012-10-25,1108561013,143.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,Think on your sins.,Skyfall,6.9,7604

In [4]:
movies=movies.merge(credits,on='title')

In [5]:
#geres
#id
#keyword
#title
#overview
#caste
#crew
movies=movies[['title','movie_id','overview','genres','keywords','cast','crew']]

In [6]:
movies.isnull().sum()

title       0
movie_id    0
overview    3
genres      0
keywords    0
cast        0
crew        0
dtype: int64

In [7]:
movies.dropna(inplace=True)

In [8]:
movies.duplicated().sum()

0

In [9]:
movies.iloc[0].genres

'[{"id": 28, "name": "Action"}, {"id": 12, "name": "Adventure"}, {"id": 14, "name": "Fantasy"}, {"id": 878, "name": "Science Fiction"}]'

In [10]:
# '[{"id": 28, "name": "Action"}, {"id": 12, "name": "Adventure"}, {"id": 14, "name": "Fantasy"}, {"id": 878, "name": "Science Fiction"}]'

In [11]:
import ast
def convert(obj):
    L=[]
    for i in ast.literal_eval(obj):
        L.append(i['name'])
    return L

In [12]:
movies['genres']=movies['genres'].apply(convert)

In [13]:
movies['keywords']=movies['keywords'].apply(convert)

In [14]:
movies.head()

,title,movie_id,overview,genres,keywords,cast,crew
0,Avatar,19995,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,Pirates of the Caribbean: At World's End,285,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,Spectre,206647,A cryptic message from Bondâ€™s past sends him o...,"[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,The Dark Knight Rises,49026,Following the death of District Attorney Harve...,"[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...","[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,John Carter,49529,"John Carter is a war-weary, former military ca...","[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [15]:
def convert3(obj):
    L=[]
    counter =0
    for i in ast.literal_eval(obj):
        if counter!=3:
            L.append(i['name'])
            counter+=1
        else:
            break
    return L

In [16]:
movies['cast']=movies['cast'].apply(convert3)

In [17]:
movies.head()

,title,movie_id,overview,genres,keywords,cast,crew
0,Avatar,19995,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[Sam Worthington, Zoe Saldana, Sigourney Weaver]","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,Pirates of the Caribbean: At World's End,285,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[Johnny Depp, Orlando Bloom, Keira Knightley]","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,Spectre,206647,A cryptic message from Bondâ€™s past sends him o...,"[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...","[Daniel Craig, Christoph Waltz, LÃ©a Seydoux]","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,The Dark Knight Rises,49026,Following the death of District Attorney Harve...,"[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...","[Christian Bale, Michael Caine, Gary Oldman]","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,John Carter,49529,"John Carter is a war-weary, former military ca...","[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","[Taylor Kitsch, Lynn Collins, Samantha Morton]","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [18]:
def fetchdirector(obj):
    L=[]
    for i in ast.literal_eval(obj):
        if i['job']=='Director':
            L.append(i['name'])
            break
    return L

In [19]:
movies['crew']=movies['crew'].apply(fetchdirector)

In [20]:
movies.head()

,title,movie_id,overview,genres,keywords,cast,crew
0,Avatar,19995,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[Sam Worthington, Zoe Saldana, Sigourney Weaver]",[James Cameron]
1,Pirates of the Caribbean: At World's End,285,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[Johnny Depp, Orlando Bloom, Keira Knightley]",[Gore Verbinski]
2,Spectre,206647,A cryptic message from Bondâ€™s past sends him o...,"[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...","[Daniel Craig, Christoph Waltz, LÃ©a Seydoux]",[Sam Mendes]
3,The Dark Knight Rises,49026,Following the death of District Attorney Harve...,"[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...","[Christian Bale, Michael Caine, Gary Oldman]",[Christopher Nolan]
4,John Carter,49529,"John Carter is a war-weary, former military ca...","[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","[Taylor Kitsch, Lynn Collins, Samantha Morton]",[Andrew Stanton]

In [21]:
movies['overview']=movies['overview'].apply(lambda x:x.split() )

In [22]:
movies.head()

,title,movie_id,overview,genres,keywords,cast,crew
0,Avatar,19995,"[In, the, 22nd, century,, a, paraplegic, Marin...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[Sam Worthington, Zoe Saldana, Sigourney Weaver]",[James Cameron]
1,Pirates of the Caribbean: At World's End,285,"[Captain, Barbossa,, long, believed, to, be, d...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[Johnny Depp, Orlando Bloom, Keira Knightley]",[Gore Verbinski]
2,Spectre,206647,"[A, cryptic, message, from, Bondâ€™s, past, send...","[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...","[Daniel Craig, Christoph Waltz, LÃ©a Seydoux]",[Sam Mendes]
3,The Dark Knight Rises,49026,"[Following, the, death, of, District, Attorney...","[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...","[Christian Bale, Michael Caine, Gary Oldman]",[Christopher Nolan]
4,John Carter,49529,"[John, Carter, is, a, war-weary,, former, mili...","[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","[Taylor Kitsch, Lynn Collins, Samantha Morton]",[Andrew Stanton]

In [23]:
movies['genres']=movies['genres'].apply(lambda x:[i.replace(" ","") for i in x])
movies['keywords']=movies['keywords'].apply(lambda x:[i.replace(" ","") for i in x])
movies['cast']=movies['cast'].apply(lambda x:[i.replace(" ","") for i in x])
movies['crew']=movies['crew'].apply(lambda x:[i.replace(" ","") for i in x])

In [24]:
movies.head()

,title,movie_id,overview,genres,keywords,cast,crew
0,Avatar,19995,"[In, the, 22nd, century,, a, paraplegic, Marin...","[Action, Adventure, Fantasy, ScienceFiction]","[cultureclash, future, spacewar, spacecolony, ...","[SamWorthington, ZoeSaldana, SigourneyWeaver]",[JamesCameron]
1,Pirates of the Caribbean: At World's End,285,"[Captain, Barbossa,, long, believed, to, be, d...","[Adventure, Fantasy, Action]","[ocean, drugabuse, exoticisland, eastindiatrad...","[JohnnyDepp, OrlandoBloom, KeiraKnightley]",[GoreVerbinski]
2,Spectre,206647,"[A, cryptic, message, from, Bondâ€™s, past, send...","[Action, Adventure, Crime]","[spy, basedonnovel, secretagent, sequel, mi6, ...","[DanielCraig, ChristophWaltz, LÃ©aSeydoux]",[SamMendes]
3,The Dark Knight Rises,49026,"[Following, the, death, of, District, Attorney...","[Action, Crime, Drama, Thriller]","[dccomics, crimefighter, terrorist, secretiden...","[ChristianBale, MichaelCaine, GaryOldman]",[ChristopherNolan]
4,John Carter,49529,"[John, Carter, is, a, war-weary,, former, mili...","[Action, Adventure, ScienceFiction]","[basedonnovel, mars, medallion, spacetravel, p...","[TaylorKitsch, LynnCollins, SamanthaMorton]",[AndrewStanton]

In [25]:
movies['tags']=movies['keywords']+movies['genres']+movies['cast']+movies['crew']+movies['overview']

In [26]:
movies.head()

,title,movie_id,overview,genres,keywords,cast,crew,tags
0,Avatar,19995,"[In, the, 22nd, century,, a, paraplegic, Marin...","[Action, Adventure, Fantasy, ScienceFiction]","[cultureclash, future, spacewar, spacecolony, ...","[SamWorthington, ZoeSaldana, SigourneyWeaver]",[JamesCameron],"[cultureclash, future, spacewar, spacecolony, ..."
1,Pirates of the Caribbean: At World's End,285,"[Captain, Barbossa,, long, believed, to, be, d...","[Adventure, Fantasy, Action]","[ocean, drugabuse, exoticisland, eastindiatrad...","[JohnnyDepp, OrlandoBloom, KeiraKnightley]",[GoreVerbinski],"[ocean, drugabuse, exoticisland, eastindiatrad..."
2,Spectre,206647,"[A, cryptic, message, from, Bondâ€™s, past, send...","[Action, Adventure, Crime]","[spy, basedonnovel, secretagent, sequel, mi6, ...","[DanielCraig, ChristophWaltz, LÃ©aSeydoux]",[SamMendes],"[spy, basedonnovel, secretagent, sequel, mi6, ..."
3,The Dark Knight Rises,49026,"[Following, the, death, of, District, Attorney...","[Action, Crime, Drama, Thriller]","[dccomics, crimefighter, terrorist, secretiden...","[ChristianBale, MichaelCaine, GaryOldman]",[ChristopherNolan],"[dccomics, crimefighter, terrorist, secretiden..."
4,John Carter,49529,"[John, Carter, is, a, war-weary,, former, mili...","[Action, Adventure, ScienceFiction]","[basedonnovel, mars, medallion, spacetravel, p...","[TaylorKitsch, LynnCollins, SamanthaMorton]",[AndrewStanton],"[basedonnovel, mars, medallion, spacetravel, p..."

In [27]:
new_df=movies[['movie_id' , 'title','tags']]

In [28]:
new_df

,movie_id,title,tags
0,19995,Avatar,"[cultureclash, future, spacewar, spacecolony, ..."
1,285,Pirates of the Caribbean: At World's End,"[ocean, drugabuse, exoticisland, eastindiatrad..."
2,206647,Spectre,"[spy, basedonnovel, secretagent, sequel, mi6, ..."
3,49026,The Dark Knight Rises,"[dccomics, crimefighter, terrorist, secretiden..."
4,49529,John Carter,"[basedonnovel, mars, medallion, spacetravel, p..."
...,...,...,...
4804,9367,El Mariachi,"[unitedstatesâ€“mexicobarrier, legs, arms, paper..."
4805,72766,Newlyweds,"[Comedy, Romance, EdwardBurns, KerryBishÃ©, Mar..."
4806,231617,"Signed, Sealed, Delivered","[date, loveatfirstsight, narration, investigat..."
4807,126186,Shanghai Calling,"[DanielHenney, ElizaCoupe, BillPaxton, DanielH..."
4808,25975,My Date with Drew,"[obsession, camcorder, crush, dreamgirl, Docum..."

In [29]:
new_df['tags']=new_df['tags'].apply(lambda x:" ".join(x))

C:\Users\AMAN TIWARI\AppData\Local\Temp\ipykernel_25332\487797088.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags']=new_df['tags'].apply(lambda x:" ".join(x))

In [30]:
new_df['tags']=new_df['tags'].apply(lambda x:x.lower())

C:\Users\AMAN TIWARI\AppData\Local\Temp\ipykernel_25332\4224080999.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags']=new_df['tags'].apply(lambda x:x.lower())

In [31]:
new_df.head()

,movie_id,title,tags
0,19995,Avatar,cultureclash future spacewar spacecolony socie...
1,285,Pirates of the Caribbean: At World's End,ocean drugabuse exoticisland eastindiatradingc...
2,206647,Spectre,spy basedonnovel secretagent sequel mi6 britis...
3,49026,The Dark Knight Rises,dccomics crimefighter terrorist secretidentity...
4,49529,John Carter,basedonnovel mars medallion spacetravel prince...

In [32]:
import nltk
from nltk.stem.porter import PorterStemmer
ps=PorterStemmer()

In [33]:
def stem(text):
    y=[]
    for i in text.split():
        y.append(ps.stem(i))
    return " ".join(y)

In [34]:
new_df['tags'][0]

'cultureclash future spacewar spacecolony society spacetravel futuristic romance space alien tribe alienplanet cgi marine soldier battle loveaffair antiwar powerrelations mindandsoul 3d action adventure fantasy sciencefiction samworthington zoesaldana sigourneyweaver jamescameron in the 22nd century, a paraplegic marine is dispatched to the moon pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization.'

In [35]:
new_df['tags']=new_df['tags'].apply(stem)

C:\Users\AMAN TIWARI\AppData\Local\Temp\ipykernel_25332\3514595201.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags']=new_df['tags'].apply(stem)

In [36]:

from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features=5000,stop_words='english')

In [37]:
vectors=cv.fit_transform(new_df['tags']).toarray()

In [38]:
vectors[0]

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [39]:
cv.get_feature_names()

C:\Python310\lib\site-packages\sklearn\utils\deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)

['000',
 '007',
 '10',
 '100',
 '11',
 '12',
 '13',
 '14',
 '15',
 '16',
 '17',
 '17th',
 '18',
 '18th',
 '18thcenturi',
 '19',
 '1910',
 '1920',
 '1930',
 '1940',
 '1944',
 '1950',
 '1950s',
 '1960',
 '1960s',
 '1970',
 '1970s',
 '1971',
 '1974',
 '1976',
 '1980',
 '1985',
 '1990',
 '1999',
 '19th',
 '19thcenturi',
 '20',
 '200',
 '2003',
 '2009',
 '20th',
 '21st',
 '23',
 '24',
 '25',
 '30',
 '300',
 '3d',
 '40',
 '50',
 '500',
 '60',
 '70',
 '80',
 'aaron',
 'aaroneckhart',
 'abandon',
 'abduct',
 'abigailbreslin',
 'abil',
 'abl',
 'aboard',
 'abov',
 'abus',
 'academ',
 'academi',
 'accept',
 'access',
 'accid',
 'accident',
 'acclaim',
 'accompani',
 'accomplish',
 'account',
 'accus',
 'ace',
 'achiev',
 'acquaint',
 'act',
 'action',
 'actionhero',
 'activ',
 'activist',
 'activities',
 'actor',
 'actress',
 'actual',
 'ad',
 'adam',
 'adamsandl',
 'adamshankman',
 'adapt',
 'add',
 'addict',
 'adjust',
 'admir',
 'admit',
 'adolesc',
 'adopt',
 'ador',
 'adrienbrodi',
 'adult',
 'adultanim',
 'adulteri',
 'adulthood',
 'advanc',
 'adventur',
 'adventure',
 'adventures',
 'advertis',
 'advic',
 'advis',
 'affair',
 'affect',
 'afghanistan',
 'africa',
 'african',
 'africanamerican',
 'aftercreditssting',
 'afterlif',
 'aftermath',
 'ag',
 'age',
 'agediffer',
 'agenc',
 'agency',
 'agenda',
 'agent',
 'agents',
 'aggress',
 'ago',
 'agre',
 'ahead',
 'aid',
 'aidanquinn',
 'ail',
 'aim',
 'air',
 'airplan',
 'airplanecrash',
 'airport',
 'aka',
 'al',
 'alabama',
 'alan',
 'alaska',
 'albert',
 'alcatraz',
 'alcohol',
 'alecbaldwin',
 'alex',
 'alexkendrick',
 'alfredhitchcock',
 'alfredmolina',
 'ali',
 'alic',
 'alice',
 'alien',
 'alieninvas',
 'alienlife',
 'alienplanet',
 'aliens',
 'alik',
 'aliv',
 'alive',
 'allen',
 'alli',
 'allianc',
 'allow',
 'alon',
 'alongsid',
 'alpacino',
 'alpha',
 'alreadi',
 'alter',
 'altern',
 'alway',
 'alyssa',
 'alzheimer',
 'amanda',
 'amandapeet',
 'amandaseyfri',
 'amateur',
 'amaz',
 'amazon',
 'ambassador',
 'ambit',
 'ambiti',
 'ambul',
 'ambush',
 'america',
 'american',
 'americanabroad',
 'americancivilwar',
 'americanfootbal',
 'americanfootballplay',
 'amid',
 'amidst',
 'amnesia',
 'amp',
 'amsterdam',
 'amus',
 'amusementpark',
 'amy',
 'amyadam',
 'amysmart',
 'ana',
 'anakin',
 'analyst',
 'anarchiccomedi',
 'ancient',
 'ancientrom',
 'ancientworld',
 'anderson',
 'andi',
 'andiemacdowel',
 'andrew',
 'android',
 'andy',
 'andygarcÃ­a',
 'angel',
 'angela',
 'angelabassett',
 'angeles',
 'angelinajoli',
 'anger',
 'angle',
 'angri',
 'ani',
 'anim',
 'animalattack',
 'animalhorror',
 'animals',
 'anjelicahuston',
 'ann',
 'anna',
 'annafari',
 'annakendrick',
 'anne',
 'annehathaway',
 'annemoss',
 'annetteben',
 'anni',
 'annie',
 'anniversari',
 'announc',
 'annual',
 'anonym',
 'anoth',
 'answer',
 'ant',
 'antholog',
 'anthoni',
 'anthonyanderson',
 'anthonyhopkin',
 'anthropomorph',
 'anti',
 'antic',
 'antihero',
 'antiqu',
 'antoinefuqua',
 'antoniobandera',
 'antonyelchin',
 'anyon',
 'anyth',
 'apart',
 'apartheid',
 'apartment',
 'ape',
 'apocalyps',
 'apocalypse',
 'apocalypt',
 'appar',
 'appear',
 'appl',
 'apple',
 'appoint',
 'appreci',
 'apprentic',
 'approach',
 'april',
 'aquarium',
 'arab',
 'arch',
 'archaeologist',
 'archeolog',
 'archer',
 'architect',
 'arctic',
 'area',
 'aren',
 'arena',
 'argument',
 'aris',
 'aristocrat',
 'arm',
 'armi',
 'armor',
 'armsdeal',
 'army',
 'arnold',
 'arnoldschwarzenegg',
 'arrang',
 'arrangedmarriag',
 'arrest',
 'arriv',
 'arrog',
 'art',
 'arthur',
 'artifact',
 'artifici',
 'artificialintellig',
 'artist',
 'ash',
 'ashley',
 'ashleyjudd',
 'ashtonkutch',
 'asia',
 'asian',
 'asid',
 'ask',
 'aspect',
 'aspir',
 'assassin',
 'assault',
 'assembl',
 'assign',
 'assist',
 'assistant',
 'associ',
 'assum',
 'asteroid',
 'astronaut',
 'asylum',
 'atheist',
 'athlet',
 'atom',
 'atomicbomb',
 'attack',
 'attacks',
 'attempt',
 'attend',
 'attent',
 'attic',
 'attitud',
 'attorney',
 'attract',
 'auction',
 'audienc',
 'audit',
 'august',
 'aunt',
 'austin',
 'australia',
 'australian',
 'author',
 'autism',
 'auto',
 'automobilerac',
 'aveng',
 'averag',
 'avoid',
 'await',
 'awak',
 'awaken',
 'awar',
 'award',
 'away',
 'awkward',
 'awri',
 'awry',
 'ax',
 'babe',
 'babi',
 'baby',
 'bachelor',
 'backdrop',
 'background',
 'backpack',
 'bad',
 'bag',
 'bahama',
 'bail',
 'balanc',
 'ball',
 'ballet',
 'balloon',
 'baltimor',
 'ban',
 'band',
 'bandit',
 'bangkok',
 'banish',
 'bank',
 'banker',
 'bankrobb',
 'bankrobberi',
 'bar',
 'barbrastreisand',
 'bare',
 'bargain',
 'barn',
 'barney',
 'baron',
 'barri',
 'barrylevinson',
 'barrysonnenfeld',
 'bas',
 'base',
 'basebal',
 'basedoncomicbook',
 'basedongraphicnovel',
 'basedonnovel',
 'basedonplay',
 'basedonstagemus',
 'basedontrueev',
 'basedontruestori',
 'basedontvseri',
 'basedonvideogam',
 'basedonyoungadultnovel',
 'basement',
 'basketbal',
 'basketball',
 'bat',
 'batman',
 'battl',
 'battle',
 'battlefield',
 'bay',
 'beach',
 'beam',
 'bear',
 'beard',
 'beast',
 'beat',
 'beauti',
 'beautiful',
 'beautifulwoman',
 'beauty',
 'becam',
 'becaus',
 'becki',
 'becom',
 'becominganadult',
 'bed',
 'bedroom',
 'bee',
 'beer',
 'befor',
 'befriend',
 'began',
 'begin',
 'begins',
 'behavior',
 'belief',
 'believ',
 'bell',
 'bella',
 'belong',
 'belov',
 'ben',
 'benaffleck',
 'bend',
 'beneath',
 'benefit',
 'benfost',
 'beniciodeltoro',
 'benjamin',
 'benjaminbratt',
 'benkingsley',
 'bennett',
 'benstil',
 'bent',
 'berlin',
 'best',
 'bestfriend',
 'bestfriendsinlov',
 'bet',
 'beth',
 'betray',
 'bettemidl',
 'better',
 'betti',
 'beverli',
 'bibl',
 'bid',
 'big',
 'bigger',
 'biggest',
 'bike',
 'biker',
 'bikini',
 'billhad',
 'billi',
 'billionair',
 'billmurray',
 'billnighi',
 'billpaxton',
 'billpullman',
 'billybobthornton',
 'billycrudup',
 'billycryst',
 'biographi',
 'biolog',
 'bird',
 'birth',
 'birthday',
 'bisexu',
 'bishop',
 'bit',
 'bite',
 'bitter',
 'bizarr',
 'black',
 'blackmag',
 'blackmail',
 'blackpeopl',
 'blacksmith',
 'blade',
 'blame',
 'blend',
 'blind',
 'bliss',
 'blizzard',
 'block',
 'blond',
 'blood',
 'bloodi',
 'bloodsplatt',
 'bloodthirsti',
 'blow',
 'blue',
 'board',
 'boardingschool',
 'boat',
 'bob',
 'bobbi',
 'bobbyfarrelli',
 'bobhoskin',
 'bodi',
 'body',
 'bodyguard',
 'bold',
 'bollywood',
 'bomb',
 'bond',
 'bone',
 'book',
 'border',
 'bore',
 'boredom',
 'born',
 'boss',
 'boston',
 'botch',
 'bound',
 'boundari',
 'bounti',
 'bountyhunt',
 'bout',
 'box',
 'boxer',
 'boy',
 'boyfriend',
 'boys',
 'bradleycoop',
 'bradpitt',
 'brain',
 'brainwash',
 'brand',
 'brandon',
 'brave',
 'braveri',
 'brazil',
 'brazilian',
 'break',
 'breakdown',
 'breast',
 'breath',
 'breed',
 'brendanfras',
 'brendangleeson',
 'brent',
 'brettratn',
 'brian',
 'briandepalma',
 'bride',
 'bridesmaid',
 'bridg',
 'brief',
 'brielarson',
 'brien',
 'bright',
 'brilliant',
 'bring',
 'brink',
 'britain',
 'british',
 'britishsecretservic',
 'brittanymurphi',
 'broadcast',
 'broadway',
 'broke',
 'broken',
 'broker',
 'bronx',
 'brook',
 'brooklyn',
 'broom',
 'brothel',
 'brother',
 'brotherbrotherrelationship',
 'brothers',
 'brothersisterrelationship',
 'brought',
 'brown',
 'bruce',
 'brucegreenwood',
 'brucewilli',
 'brutal',
 'bryansing',
 'bu',
 'buck',
 'bud',
 'buddi',
 'buddy',
 'buddycomedi',
 'buddycop',
 'budget',
 'build',
 'building',
 'built',
 'bullet',
 'bulli',
 'bumbl',
 'bunch',
 'bunker',
 'bunni',
 'burglar',
 'buri',
 'burn',
 'bush',
 'busi',
 'business',
 'businessman',
 'bust',
 'butcher',
 'butler',
 'butt',
 'button',
 'buy',
 'buzz',
 'cabin',
 'caesar',
 'cage',
 'cairo',
 'cal',
 'california',
 'calvin',
 'camcord',
 'came',
 'camera',
 'cameraman',
 'camerondiaz',
 'camp',
 'campaign',
 'campbell',
 'campu',
 'canada',
 'canadian',
 'cancer',
 'candi',
 'candid',
 'canin',
 'cannib',
 'canuxploit',
 'capabl',
 'caper',
 'capit',
 'capt',
 'captain',
 'captiv',
 'captur',
 'capture',
 'car',
 'caraccid',
 'carchas',
 'carcrash',
 'card',
 'care',
 'career',
 'carefre',
 'caretak',
 'careymulligan',
 'caribbean',
 'carjourney',
 'carl',
 'carlagugino',
 'carmen',
 'carol',
 'carolina',
 'carrac',
 'carri',
 'carrie',
 'cartel',
 'carter',
 'cartoon',
 'caryelw',
 'case',
 'caseyaffleck',
 'cash',
 'casino',
 'cast',
 'castl',
 'cat',
 'cataclysm',
 'catastroph',
 'catch',
 'cateblanchett',
 'catherinedeneuv',
 'catherinekeen',
 'catherinezeta',
 'cathol',
 'catholic',
 'cattl',
 'caught',
 'caus',
 'cavalri',
 'cave',
 'cavemen',
 'celebr',
 'celebration',
 'cell',
 'cellphon',
 'cemeteri',
 'center',
 'centr',
 'central',
 'centuri',
 'centuries',
 'century',
 'ceo',
 'certain',
 'chad',
 'chain',
 'chainsaw',
 'challeng',
 'chamber',
 'champion',
 'championship',
 'chanc',
 'chance',
 'chang',
 'change',
 'changed',
 'changes',
 'channingtatum',
 'chao',
 'chaos',
 'chaotic',
 'chapter',
 'charact',
 'character',
 'characters',
 'charg',
 'charismat',
 'charl',
 'charli',
 'charlie',
 'charliesheen',
 'charlizetheron',
 'charm',
 'chart',
 'chase',
 'chauffeur',
 'chazzpalminteri',
 'cheat',
 'check',
 'cheerlead',
 'chef',
 'chemic',
 'cher',
 'chevychas',
 'chicago',
 'chicken',
 'chief',
 'child',
 'childabus',
 'childhero',
 'childhood',
 'childprodigi',
 'children',
 'chill',
 'chimp',
 'china',
 'chines',
 'chip',
 'chipmunk',
 'chiwetelejiofor',
 'chloe',
 'chloÃ«gracemoretz',
 'chloÃ«sevigni',
 'chocol',
 'choic',
 'choice',
 'choos',
 'chosen',
 'chowyun',
 'chri',
 'chriscolumbu',
 'chriscoop',
 'chrisevan',
 'chrishemsworth',
 'chrisklein',
 'chrispin',
 'chrisrock',
 'christ',
 'christian',
 'christianbal',
 'christianslat',
 'christin',
 'christinaappleg',
 'christinaricci',
 'christma',
 'christmas',
 'christmasparti',
 'christmastre',
 'christoph',
 'christopherlambert',
 'christopherlloyd',
 'christophernolan',
 'christopherplumm',
 'christopherwalken',
 'christophwaltz',
 'chrisweitz',
 'chronicl',
 'chuck',
 'church',
 'cia',
 'ciarÃ¡nhind',
 'cigarettesmok',
 'cillianmurphi',
 'cinema',
 'circl',
 'circu',
 'circuit',
 'circumst',
 'citi',
 'citizen',
 'city',
 'civil',
 'civilian',
 'civilwar',
 'claim',
 'clair',
 'clairedan',
 'claireforlani',
 'clan',
 'clark',
 'clash',
 'class',
 'classdiffer',
 'classic',
 'classmat',
 'classroom',
 'claudevandamm',
 'clay',
 'clean',
 'clear',
 'clerk',
 'clever',
 'client',
 'clients',
 'cliff',
 'climat',
 'climb',
 'clinteastwood',
 'cliveowen',
 'clock',
 'clone',
 'close',
 'closer',
 'cloud',
 'clown',
 'club',
 'clue',
 'clueless',
 'clutch',
 'coach',
 'coast',
 'cocain',
 'code',
 'coffin',
 'cohen',
 'col',
 'cold',
 'coldwar',
 'cole',
 'colin',
 'colinfarrel',
 'colinfirth',
 'collaps',
 'colleagu',
 'collect',
 'collector',
 'colleg',
 'college',
 'collid',
 'collis',
 'colombia',
 'colonel',
 'coloni',
 'color',
 'colorado',
 'coma',
 'combat',
 'combin',
 'come',
 'comeback',
 'comed',
 'comedi',
 'comedian',
 'comedy',
 'comet',
 'comfort',
 'comic',
 'coming',
 'comingofag',
 'comingout',
 'command',
 'commando',
 'commerci',
 'commiss',
 'commit',
 'common',
 'commun',
 'communist',
 'community',
 'compani',
 'companion',
 'company',
 'compet',
 'competit',
 'competition',
 'complet',
 'complex',
 'complic',
 'compos',
 'compuls',
 'comput',
 'computerviru',
 'conan',
 'concern',
 'concert',
 'concoct',
 'condit',
 'condition',
 'conduct',
 'confeder',
 'confess',
 'confid',
 'confin',
 'conflict',
 'confront',
 'confus',
 'congress',
 'conman',
 'connect',
 'connecticut',
 'connel',
 'connor',
 'conquer',
 'consequ',
 'consequences',
 'conserv',
 'consid',
 'conspir',
 'conspiraci',
 'conspiracy',
 'constant',
 'constantli',
 'construct',
 'consum',
 'contact',
 'contain',
 'contemporari',
 'contend',
 'content',
 'contest',
 'continu',
 'contract',
 'contractor',
 'control',
 'controversi',
 'convent',
 'converg',
 'convers',
 'convict',
 'convinc',
 'cook',
 ...]

In [40]:
from sklearn.metrics.pairwise import cosine_similarity

In [41]:
similarity=cosine_similarity(vectors)

In [44]:
new_df[new_df['title'] == 'The Lego Movie'].index[0]

744

In [45]:
sorted(list(enumerate(similarity[0])),reverse=True,key=lambda x:x[1])[1:6]

[(1216, 0.28676966733820225),
 (2409, 0.26901379342448517),
 (3730, 0.2605130246476754),
 (507, 0.255608593705383),
 (539, 0.25038669783359574)]

In [50]:
def recommend(movie):
    index = new_df[new_df['title'] == movie].index[0]
    distances = sorted(list(enumerate(similarity[index])),reverse=True,key = lambda x: x[1])
    for i in distances[1:6]:
        print(new_df.iloc[i[0]].title)

In [51]:
recommend('Avatar')

Aliens vs Predator: Requiem
Aliens
Falcon Rising
Independence Day
Titan A.E.

In [52]:
recommend('Gandhi')

Gandhi, My Father
Guiana 1838
The Wind That Shakes the Barley
Mr. Turner
The Sea Inside